GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jaska Jokunen",
    "number": "0100100"
}

###

GET http://localhost:3001/info

###

DELETE http://localhost:3001/api/persons/6402170b840cb59291ad2eb1

###

HEAD http://localhost:3001/info
