
GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jaska Jokunen",
    "number": "0100100"
}

###

GET http://localhost:3001/info

###

DELETE http://localhost:3001/api/persons/6402f26896d6685454c11579

###

HEAD http://localhost:3001/info

###

PUT http://localhost:3001/api/persons/64033c27e72999af8fd13314
Content-Type: application/json

{
    "name": "Joku toinen",
    "number": "9090999"
}

###

GET http://localhost:3001/api/persons/64033c27e72999af8fd13314

###
